spring:
  application:
    name: eureka
server:
  port: 8760

eureka:
  client:
    register-with-eureka: true   # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    fetch-registry: true         # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    serviceUrl:
        defaultZone: http://localhost:${server.port}/eureka/
  instance:
     statusPageUrl: http://${eureka.hostname}/info      #实例状态页面
     healthCheckUrl: http://${eureka.hostname}/health   #运行状态指示器
     homePageUrl: http://${eureka.hostname}/
